version: '3.5'
services:
  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "4567:4567/tcp"

  nginx:
    image: nginx
    ports:
      - "$APP_PORT:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx-my.conf
    environment:
      - APP_PORT
    command: /bin/bash -c "envsubst < /etc/nginx/nginx-my.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
